### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by qsdj** [ztgrace/changeme#40] opened 2017-09-27 03:02 UTC
> [22:50:42][scan_engine][fingerprint_targets] 9906 fingerprints remaining
[22:50:52][scan_engine][fingerprint_targets] Caught exception: OperationalError
[22:50:52][scan_engine][fingerprint_targets] Exception: OperationalError: database is locked
[22:50:53][scan_engine][fingerprint_targets] 9906 fingerprints remaining
[22:51:03][scan_engine][fingerprint_targets] Caught exception: OperationalError
[22:51:03][scan_engine][fingerprint_targets] Exception: OperationalError: database is locked
[22:51:03][scan_engine][scan] Fingerprinting completed
Traceback (most recent call last):
  File "changeme.py", line 6, in <module>
    core.main()
  File "/home/root/Desktop/changeme/changeme/core.py", line 69, in main
    s.scan()
  File "/home/root/Desktop/changeme/changeme/scan_engine.py", line 63, in scan
    while self.scanners.qsize() > 0:
  File "/usr/local/lib/python2.7/dist-packages/persistqueue/sqlqueue.py", line 84, in qsize
    return self.size
  File "/usr/local/lib/python2.7/dist-packages/persistqueue/sqlqueue.py", line 81, in size
    return self._count()
  File "/usr/local/lib/python2.7/dist-packages/persistqueue/sqlbase.py", line 121, in _count
    row = self._putter.execute(sql).fetchone()
sqlite3.OperationalError: database is locked

Hi brother, I have this problem. How can I solve this problem? thank you ！

**Comment by ztgrace** [comment] 2017-09-27 12:04
Hi @qsdj - Please install a redis server for better performance. As this is a duplicate of #38 I'm closing this issue.

**Closed by ztgrace** 2017-09-27 12:04 UTC
Labels: bug, duplicate
